In [ ]:
import numpy as np
import pandas as pd
import plotly.express as px

In [5]:
df = pd.read_csv('DataCoSupplyChainDataset.csv', encoding='ISO-8859-1')
df

,Type,Days for shipping (real),Days for shipment (scheduled),Benefit per order,Sales per customer,Delivery Status,Late_delivery_risk,Category Id,Category Name,Customer City,...,Order Zipcode,Product Card Id,Product Category Id,Product Description,Product Image,Product Name,Product Price,Product Status,shipping date (DateOrders),Shipping Mode
0,DEBIT,3,4,91.250000,314.640015,Advance shipping,0,73,Sporting Goods,Caguas,...,NaN,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.750000,0,2/3/2018 22:56,Standard Class
1,TRANSFER,5,4,-249.089996,311.359985,Late delivery,1,73,Sporting Goods,Caguas,...,NaN,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.750000,0,1/18/2018 12:27,Standard Class
2,CASH,4,4,-247.779999,309.720001,Shipping on time,0,73,Sporting Goods,San Jose,...,NaN,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.750000,0,1/17/2018 12:06,Standard Class
3,DEBIT,3,4,22.860001,304.809998,Advance shipping,0,73,Sporting Goods,Los Angeles,...,NaN,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.750000,0,1/16/2018 11:45,Standard Class
4,PAYMENT,2,4,134.210007,298.250000,Advance shipping,0,73,Sporting Goods,Caguas,...,NaN,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.750000,0,1/15/2018 11:24,Standard Class
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
180514,CASH,4,4,40.000000,399.980011,Shipping on time,0,45,Fishing,Brooklyn,...,NaN,1004,45,NaN,http://images.acmesports.sports/Field+%26+Stre...,Field & Stream Sportsman 16 Gun Fire Safe,399.980011,0,1/20/2016 3:40,Standard Class
180515,DEBIT,3,2,-613.770019,395.980011,Late delivery,1,45,Fishing,Bakersfield,...,NaN,1004,45,NaN,http://images.acmesports.sports/Field+%26+Stre...,Field & Stream Sportsman 16 Gun Fire Safe,399.980011,0,1/19/2016 1:34,Second Class
180516,TRANSFER,5,4,141.110001,391.980011,Late delivery,1,45,Fishing,Bristol,...,NaN,1004,45,NaN,http://images.acmesports.sports/Field+%26+Stre...,Field & Stream Sportsman 16 Gun Fire Safe,399.980011,0,1/20/2016 21:00,Standard Class
180517,PAYMENT,3,4,186.229996,387.980011,Advance shipping,0,45,Fishing,Caguas,...,NaN,1004,45,NaN,http://images.acmesports.sports/Field+%26+Stre...,Field & Stream Sportsman 16 Gun Fire Safe,399.980011,0,1/18/2016 20:18,Standard Class
180518,PAYMENT,4,4,168.949997,383.980011,Shipping on time,0,45,Fishing,Caguas,...,NaN,1004,45,NaN,http://images.acmesports.sports/Field+%26+Stre...,Field & Stream Sportsman 16 Gun Fire Safe,399.980011,0,1/19/2016 18:54,Standard Class

### Exploring Data

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 180519 entries, 0 to 180518
Data columns (total 53 columns):
 #   Column                         Non-Null Count   Dtype
---  ------                         --------------   -----
 0   Type                           180519 non-null  object
 1   Days for shipping (real)       180519 non-null  int64
 2   Days for shipment (scheduled)  180519 non-null  int64
 3   Benefit per order              180519 non-null  float64
 4   Sales per customer             180519 non-null  float64
 5   Delivery Status                180519 non-null  object
 6   Late_delivery_risk             180519 non-null  int64
 7   Category Id                    180519 non-null  int64
 8   Category Name                  180519 non-null  object
 9   Customer City                  180519 non-null  object
 10  Customer Country               180519 non-null  object
 11  Customer Email                 180519 non-null  object
 12  Customer Fname                 180519 non-null  object
 13  Customer Id                    180519 non-null  int64
 14  Customer Lname                 180511 non-null  object
 15  Customer Password              180519 non-null  object
 16  Customer Segment               180519 non-null  object
 17  Customer State                 180519 non-null  object
 18  Customer Street                180519 non-null  object
 19  Customer Zipcode               180516 non-null  float64
 20  Department Id                  180519 non-null  int64
 21  Department Name                180519 non-null  object
 22  Latitude                       180519 non-null  float64
 23  Longitude                      180519 non-null  float64
 24  Market                         180519 non-null  object
 25  Order City                     180519 non-null  object
 26  Order Country                  180519 non-null  object
 27  Order Customer Id              180519 non-null  int64
 28  order date (DateOrders)        180519 non-null  object
 29  Order Id                       180519 non-null  int64
 30  Order Item Cardprod Id         180519 non-null  int64
 31  Order Item Discount            180519 non-null  float64
 32  Order Item Discount Rate       180519 non-null  float64
 33  Order Item Id                  180519 non-null  int64
 34  Order Item Product Price       180519 non-null  float64
 35  Order Item Profit Ratio        180519 non-null  float64
 36  Order Item Quantity            180519 non-null  int64
 37  Sales                          180519 non-null  float64
 38  Order Item Total               180519 non-null  float64
 39  Order Profit Per Order         180519 non-null  float64
 40  Order Region                   180519 non-null  object
 41  Order State                    180519 non-null  object
 42  Order Status                   180519 non-null  object
 43  Order Zipcode                  24840 non-null   float64
 44  Product Card Id                180519 non-null  int64
 45  Product Category Id            180519 non-null  int64
 46  Product Description            0 non-null       float64
 47  Product Image                  180519 non-null  object
 48  Product Name                   180519 non-null  object
 49  Product Price                  180519 non-null  float64
 50  Product Status                 180519 non-null  int64
 51  shipping date (DateOrders)     180519 non-null  object
 52  Shipping Mode                  180519 non-null  object
dtypes: float64(15), int64(14), object(24)
memory usage: 73.0+ MB

In [7]:
df.describe()

,Days for shipping (real),Days for shipment (scheduled),Benefit per order,Sales per customer,Late_delivery_risk,Category Id,Customer Id,Customer Zipcode,Department Id,Latitude,...,Order Item Quantity,Sales,Order Item Total,Order Profit Per Order,Order Zipcode,Product Card Id,Product Category Id,Product Description,Product Price,Product Status
count,180519.000000,180519.000000,180519.000000,180519.000000,180519.000000,180519.000000,180519.000000,180516.000000,180519.000000,180519.000000,...,180519.000000,180519.000000,180519.000000,180519.000000,24840.000000,180519.000000,180519.000000,0.0,180519.000000,180519.0
mean,3.497654,2.931847,21.974989,183.107609,0.548291,31.851451,6691.379495,35921.126914,5.443460,29.719955,...,2.127638,203.772096,183.107609,21.974989,55426.132327,692.509764,31.851451,NaN,141.232550,0.0
std,1.623722,1.374449,104.433526,120.043670,0.497664,15.640064,4162.918106,37542.461122,1.629246,9.813646,...,1.453451,132.273077,120.043670,104.433526,31919.279101,336.446807,15.640064,NaN,139.732492,0.0
min,0.000000,0.000000,-4274.979980,7.490000,0.000000,2.000000,1.000000,603.000000,2.000000,-33.937553,...,1.000000,9.990000,7.490000,-4274.979980,1040.000000,19.000000,2.000000,NaN,9.990000,0.0
25%,2.000000,2.000000,7.000000,104.379997,0.000000,18.000000,3258.500000,725.000000,4.000000,18.265432,...,1.000000,119.980003,104.379997,7.000000,23464.000000,403.000000,18.000000,NaN,50.000000,0.0
50%,3.000000,4.000000,31.520000,163.990005,1.000000,29.000000,6457.000000,19380.000000,5.000000,33.144863,...,1.000000,199.919998,163.990005,31.520000,59405.000000,627.000000,29.000000,NaN,59.990002,0.0
75%,5.000000,4.000000,64.800003,247.399994,1.000000,45.000000,9779.000000,78207.000000,7.000000,39.279617,...,3.000000,299.950012,247.399994,64.800003,90008.000000,1004.000000,45.000000,NaN,199.990005,0.0
max,6.000000,4.000000,911.799988,1939.989990,1.000000,76.000000,20757.000000,99205.000000,12.000000,48.781933,...,5.000000,1999.989990,1939.989990,911.799988,99301.000000,1363.000000,76.000000,NaN,1999.989990,0.0


## Data checking of duplicates , NAN and outliers

In [8]:
df[df.duplicated()]

Empty DataFrame
Columns: [Type, Days for shipping (real), Days for shipment (scheduled), Benefit per order, Sales per customer, Delivery Status, Late_delivery_risk, Category Id, Category Name, Customer City, Customer Country, Customer Email, Customer Fname, Customer Id, Customer Lname, Customer Password, Customer Segment, Customer State, Customer Street, Customer Zipcode, Department Id, Department Name, Latitude, Longitude, Market, Order City, Order Country, Order Customer Id, order date (DateOrders), Order Id, Order Item Cardprod Id, Order Item Discount, Order Item Discount Rate, Order Item Id, Order Item Product Price, Order Item Profit Ratio, Order Item Quantity, Sales, Order Item Total, Order Profit Per Order, Order Region, Order State, Order Status, Order Zipcode, Product Card Id, Product Category Id, Product Description, Product Image, Product Name, Product Price, Product Status, shipping date (DateOrders), Shipping Mode]
Index: []

[0 rows x 53 columns]

In [9]:
col_corr = df.T.duplicated()
redundant_cols = col_corr[col_corr].index
print(redundant_cols)

Index(['Customer Password', 'Order Customer Id', 'Order Item Total',
       'Order Profit Per Order', 'Product Card Id', 'Product Category Id',
       'Product Price'],
      dtype='object')

In [10]:
df.isna().sum()

Type                                  0
Days for shipping (real)              0
Days for shipment (scheduled)         0
Benefit per order                     0
Sales per customer                    0
Delivery Status                       0
Late_delivery_risk                    0
Category Id                           0
Category Name                         0
Customer City                         0
Customer Country                      0
Customer Email                        0
Customer Fname                        0
Customer Id                           0
Customer Lname                        8
Customer Password                     0
Customer Segment                      0
Customer State                        0
Customer Street                       0
Customer Zipcode                      3
Department Id                         0
Department Name                       0
Latitude                              0
Longitude                             0
Market                                0
Order City                            0
Order Country                         0
Order Customer Id                     0
order date (DateOrders)               0
Order Id                              0
Order Item Cardprod Id                0
Order Item Discount                   0
Order Item Discount Rate              0
Order Item Id                         0
Order Item Product Price              0
Order Item Profit Ratio               0
Order Item Quantity                   0
Sales                                 0
Order Item Total                      0
Order Profit Per Order                0
Order Region                          0
Order State                           0
Order Status                          0
Order Zipcode                    155679
Product Card Id                       0
Product Category Id                   0
Product Description              180519
Product Image                         0
Product Name                          0
Product Price                         0
Product Status                        0
shipping date (DateOrders)            0
Shipping Mode                         0
dtype: int64

In [11]:
df.describe(include= ['object'])

,Type,Delivery Status,Category Name,Customer City,Customer Country,Customer Email,Customer Fname,Customer Lname,Customer Password,Customer Segment,...,Order City,Order Country,order date (DateOrders),Order Region,Order State,Order Status,Product Image,Product Name,shipping date (DateOrders),Shipping Mode
count,180519,180519,180519,180519,180519,180519,180519,180511,180519,180519,...,180519,180519,180519,180519,180519,180519,180519,180519,180519,180519
unique,4,4,50,563,2,1,782,1109,1,3,...,3597,164,65752,23,1089,9,118,118,63701,4
top,DEBIT,Late delivery,Cleats,Caguas,EE. UU.,XXXXXXXXX,Mary,Smith,XXXXXXXXX,Consumer,...,Santo Domingo,Estados Unidos,1/4/2017 2:28,Central America,Inglaterra,COMPLETE,http://images.acmesports.sports/Perfect+Fitnes...,Perfect Fitness Perfect Rip Deck,4/17/2015 22:16,Standard Class
freq,69295,98977,24551,66770,111146,180519,65150,64104,180519,93504,...,2211,24840,5,28341,6722,59491,24515,24515,10,107752

In [12]:
cat_cols = df.select_dtypes(include= 'object')
cat_cols

,Type,Delivery Status,Category Name,Customer City,Customer Country,Customer Email,Customer Fname,Customer Lname,Customer Password,Customer Segment,...,Order City,Order Country,order date (DateOrders),Order Region,Order State,Order Status,Product Image,Product Name,shipping date (DateOrders),Shipping Mode
0,DEBIT,Advance shipping,Sporting Goods,Caguas,Puerto Rico,XXXXXXXXX,Cally,Holloway,XXXXXXXXX,Consumer,...,Bekasi,Indonesia,1/31/2018 22:56,Southeast Asia,Java Occidental,COMPLETE,http://images.acmesports.sports/Smart+watch,Smart watch,2/3/2018 22:56,Standard Class
1,TRANSFER,Late delivery,Sporting Goods,Caguas,Puerto Rico,XXXXXXXXX,Irene,Luna,XXXXXXXXX,Consumer,...,Bikaner,India,1/13/2018 12:27,South Asia,Rajastán,PENDING,http://images.acmesports.sports/Smart+watch,Smart watch,1/18/2018 12:27,Standard Class
2,CASH,Shipping on time,Sporting Goods,San Jose,EE. UU.,XXXXXXXXX,Gillian,Maldonado,XXXXXXXXX,Consumer,...,Bikaner,India,1/13/2018 12:06,South Asia,Rajastán,CLOSED,http://images.acmesports.sports/Smart+watch,Smart watch,1/17/2018 12:06,Standard Class
3,DEBIT,Advance shipping,Sporting Goods,Los Angeles,EE. UU.,XXXXXXXXX,Tana,Tate,XXXXXXXXX,Home Office,...,Townsville,Australia,1/13/2018 11:45,Oceania,Queensland,COMPLETE,http://images.acmesports.sports/Smart+watch,Smart watch,1/16/2018 11:45,Standard Class
4,PAYMENT,Advance shipping,Sporting Goods,Caguas,Puerto Rico,XXXXXXXXX,Orli,Hendricks,XXXXXXXXX,Corporate,...,Townsville,Australia,1/13/2018 11:24,Oceania,Queensland,PENDING_PAYMENT,http://images.acmesports.sports/Smart+watch,Smart watch,1/15/2018 11:24,Standard Class
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
180514,CASH,Shipping on time,Fishing,Brooklyn,EE. UU.,XXXXXXXXX,Maria,Peterson,XXXXXXXXX,Home Office,...,Shanghái,China,1/16/2016 3:40,Eastern Asia,Shanghái,CLOSED,http://images.acmesports.sports/Field+%26+Stre...,Field & Stream Sportsman 16 Gun Fire Safe,1/20/2016 3:40,Standard Class
180515,DEBIT,Late delivery,Fishing,Bakersfield,EE. UU.,XXXXXXXXX,Ronald,Clark,XXXXXXXXX,Corporate,...,Hirakata,Japón,1/16/2016 1:34,Eastern Asia,Osaka,COMPLETE,http://images.acmesports.sports/Field+%26+Stre...,Field & Stream Sportsman 16 Gun Fire Safe,1/19/2016 1:34,Second Class
180516,TRANSFER,Late delivery,Fishing,Bristol,EE. UU.,XXXXXXXXX,John,Smith,XXXXXXXXX,Corporate,...,Adelaide,Australia,1/15/2016 21:00,Oceania,Australia del Sur,PENDING,http://images.acmesports.sports/Field+%26+Stre...,Field & Stream Sportsman 16 Gun Fire Safe,1/20/2016 21:00,Standard Class
180517,PAYMENT,Advance shipping,Fishing,Caguas,Puerto Rico,XXXXXXXXX,Mary,Smith,XXXXXXXXX,Consumer,...,Adelaide,Australia,1/15/2016 20:18,Oceania,Australia del Sur,PENDING_PAYMENT,http://images.acmesports.sports/Field+%26+Stre...,Field & Stream Sportsman 16 Gun Fire Safe,1/18/2016 20:18,Standard Class
180518,PAYMENT,Shipping on time,Fishing,Caguas,Puerto Rico,XXXXXXXXX,Andrea,Ortega,XXXXXXXXX,Consumer,...,Nagercoil,India,1/15/2016 18:54,South Asia,Tamil Nadu,PENDING_PAYMENT,http://images.acmesports.sports/Field+%26+Stre...,Field & Stream Sportsman 16 Gun Fire Safe,1/19/2016 18:54,Standard Class

In [13]:
num_cols = df.select_dtypes(include= 'number')
num_cols

,Days for shipping (real),Days for shipment (scheduled),Benefit per order,Sales per customer,Late_delivery_risk,Category Id,Customer Id,Customer Zipcode,Department Id,Latitude,...,Order Item Quantity,Sales,Order Item Total,Order Profit Per Order,Order Zipcode,Product Card Id,Product Category Id,Product Description,Product Price,Product Status
0,3,4,91.250000,314.640015,0,73,20755,725.0,2,18.251453,...,1,327.750000,314.640015,91.250000,NaN,1360,73,NaN,327.750000,0
1,5,4,-249.089996,311.359985,1,73,19492,725.0,2,18.279451,...,1,327.750000,311.359985,-249.089996,NaN,1360,73,NaN,327.750000,0
2,4,4,-247.779999,309.720001,0,73,19491,95125.0,2,37.292233,...,1,327.750000,309.720001,-247.779999,NaN,1360,73,NaN,327.750000,0
3,3,4,22.860001,304.809998,0,73,19490,90027.0,2,34.125946,...,1,327.750000,304.809998,22.860001,NaN,1360,73,NaN,327.750000,0
4,2,4,134.210007,298.250000,0,73,19489,725.0,2,18.253769,...,1,327.750000,298.250000,134.210007,NaN,1360,73,NaN,327.750000,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
180514,4,4,40.000000,399.980011,0,45,1005,11207.0,7,40.640930,...,1,399.980011,399.980011,40.000000,NaN,1004,45,NaN,399.980011,0
180515,3,2,-613.770019,395.980011,1,45,9141,93304.0,7,35.362545,...,1,399.980011,395.980011,-613.770019,NaN,1004,45,NaN,399.980011,0
180516,5,4,141.110001,391.980011,1,45,291,6010.0,7,41.629959,...,1,399.980011,391.980011,141.110001,NaN,1004,45,NaN,399.980011,0
180517,3,4,186.229996,387.980011,0,45,2813,725.0,7,18.213350,...,1,399.980011,387.980011,186.229996,NaN,1004,45,NaN,399.980011,0
180518,4,4,168.949997,383.980011,0,45,7547,725.0,7,18.290380,...,1,399.980011,383.980011,168.949997,NaN,1004,45,NaN,399.980011,0

In [14]:
for col in num_cols:

    print(col)
    print(df[col].nunique())
    print(df[col].unique())
    print('-' * 100)

Days for shipping (real)
7
[3 5 4 2 6 0 1]
----------------------------------------------------------------------------------------------------
Days for shipment (scheduled)
4
[4 1 2 0]
----------------------------------------------------------------------------------------------------
Benefit per order
21998
[  91.25      -249.0899963 -247.7799988 ... -103.9700012 -237.5899963
 -337.1000061]
----------------------------------------------------------------------------------------------------
Sales per customer
2927
[314.6400146 311.3599854 309.7200012 ... 298.769989  403.7099915
 474.7600098]
----------------------------------------------------------------------------------------------------
Late_delivery_risk
2
[0 1]
----------------------------------------------------------------------------------------------------
Category Id
51
[73 17 29 24 13 12  9 41 37 38 44  3 18 43 65 62 64  4  2 26 40 76 66 70
  6 11 16 36 10 63  5 60 45 59 67 61 68  7 72 69 71 75 35 34 33 32 31 30
 74 48 46]
----------------------------------------------------------------------------------------------------
Customer Id
20652
[20755 19492 19491 ... 18579 16244  2677]
----------------------------------------------------------------------------------------------------
Customer Zipcode
995
[  725. 95125. 90027. 14150. 33162. 94583. 11520. 93905.  1960.   729.
 90723. 60056. 90813. 95670. 59102. 18702. 48066. 90706. 60187. 48238.
 75220. 17013. 75228. 19702. 91402. 30318. 94539. 14609. 75211.   957.
   784.   795. 20744. 93304. 11368. 45238. 20874. 75006. 77093. 90023.
 96706.  8701. 13440. 92083. 76106. 54935. 19139. 91764. 32765. 14221.
 96822. 92056. 14120. 93611. 11434. 62040.  2155. 91766. 85281. 92703.
 17402. 80010. 93065. 20904. 55124. 78201. 19143. 19149. 10466. 27858.
  7960. 92115. 93030. 33147. 87111. 79109. 33549. 97701.  8816. 29720.
 91762. 77015. 23666. 10016. 93257. 97223. 44136. 79927. 78840. 84010.
 98031. 60620.  2360. 11691. 77088. 19124. 48227. 92840. 92105. 60609.
 92870. 95148. 44060. 95051.  7083. 90805. 92683. 33068. 91702. 33324.
  8540.  8861. 45140. 23455. 40214. 14094. 60608. 10314. 85719. 44120.
 10458. 14580. 95207. 25401. 21502. 61554. 32308. 32225.  2895. 95206.
 30058. 60453. 48213. 91801.  6511. 85029. 70065. 15301. 49423. 19067.
 38128. 98023. 92113. 60626. 10457. 60637. 91790. 93003. 20009. 33594.
 96744. 11218. 92057. 76116. 19145. 95240. 93308. 95122. 37130. 92009.
 45011. 77083. 10031. 94541.  8302. 11706. 60067. 30080. 91406. 33055.
 90046. 55106.  8817. 77520. 91342. 55337. 11746. 94087. 77478.  2135.
 58501. 20878. 96817. 30047. 84604. 38401. 30062.   745. 11212. 80219.
 48180. 48205. 44102. 63301. 95014. 65807. 92692. 90042. 30075. 48197.
 85345. 92843.  8021. 38127. 37013. 84118. 91344. 11550. 11103. 95020.
 28645. 43228. 97321.   791. 11757. 44035. 92504. 90745. 85204. 96818.
   921.   693.   680.   612.   685. 85033. 97402. 90806. 60102. 46227.
 90003. 90620. 21228. 10306. 30066.  7305. 38109. 60148. 11207.  2740.
 12550. 33175. 19446. 90037. 21206. 85035. 92833. 21218. 95823. 60614.
 27410. 95127. 44107. 97470. 95350. 10003. 92024. 95116. 95076. 83642.
 77084. 11229. 13760. 77450. 93277. 93535. 85022. 93436. 33186. 17404.
 84404. 27610. 91745.  7087. 33023. 60440. 47906.  7105. 22192. 78596.
 11432. 75243. 90201. 92109. 90638. 90065.  7047. 92691. 10002. 53704.
 94080. 19144. 33312. 89030. 80013.  1844. 92627. 60649. 21061. 45014.
 91306. 93063. 60616. 78501. 90032. 60435. 78520.  2860. 80918.  2169.
 78227.  1201. 91710. 60640. 10461. 43302. 91343. 60617. 67401. 20783.
 76180. 10977. 60643.  1841. 44130. 91761. 31907. 90063. 45013. 95035.
 91748. 90247. 60804. 97405. 90024. 27203. 54601. 63031. 91351. 14850.
 18103. 92026. 94553. 48098. 22204. 75227. 95616. 11238. 85225. 85224.
 60613. 60123. 93550. 11758. 92707. 94565.  7093. 75217. 90007. 80011.
 32822. 17331. 23452. 85301. 60641.  6082. 19134. 91706. 60657. 91709.
 19104.  8753. 60622. 95822. 48192.  7104. 11204. 96789. 10011. 11221.
 60426. 17055. 70570. 96734. 23503. 22193. 60126. 77479. 27606. 45601.
 91304. 49201. 92553. 60624. 70119. 78586. 11203. 19720.  7003. 87105.
 90001. 90630. 70117. 10040. 70072. 75052. 10467. 80631. 92111. 33165.
 44109. 80126. 80501. 23320. 80110. 60004. 33624. 46226. 90043. 95351.
  7111. 19711. 11375. 10029. 78521. 48126. 75007. 93307. 90221. 17601.
 75043. 92507. 96797. 85713. 95608. 92780. 92805. 60651. 48187. 22554.
 92126. 11419. 45044. 75240. 85308.  7052. 94015. 30127. 21234. 48224.
 33010. 90022. 11236. 53511. 27834. 75287.   603.   983.   698. 90066.
 11226. 11209. 63376. 92114. 60615. 30906. 78223. 87120. 19140. 10021.
 27514. 48823.  6902. 91765. 77036. 94544. 53215. 30044.  6040. 11224.
 91744. 92392. 23223. 63033. 21224. 32244. 78852. 92335. 63021. 11220.
 78130. 89121. 29445. 78577. 10701. 91732. 96816. 33064. 43068. 48212.
 94587. 44256. 33313. 92346. 90019. 72401. 95758. 90640. 94109. 30907.
 60025. 60647. 85282. 95111. 29730. 60660. 85746. 78753. 85254. 95060.
 97045. 22003. 38118. 75023.  8854. 33155. 23322. 92084. 92025. 30067.
 92705. 92021. 43026. 32073. 10025. 60625. 30032. 94806. 33016. 92804.
 32808. 78228. 19120. 90804. 30135. 89015. 60120. 77840. 78664. 75150.
 74012. 98052. 45840. 90631. 92653. 14215. 90057. 21215. 79912. 43230.
 92407. 27502. 94110. 23464. 91733. 80231. 89103. 75061. 11234. 24060.
  2124. 60505. 92336.  7307. 78207. 20854. 77469. 84119. 90002. 32792.
 60610. 30083. 93117. 21740. 94501. 33161. 92701. 63136. 78240. 90660.
 91910. 92882. 63116. 60619. 95124. 79924. 92020. 85032. 76010. 17603.
 76133. 95023. 91605. 55104. 78704. 90033. 94122. 60638. 11235. 62301.
 10472. 10473.  8901. 97007. 20020. 60411. 92054. 92345. 92503. 27511.
 27330. 78040. 48185. 10453. 91911. 30281. 60188. 11237. 10469. 33012.
 60634. 67212. 94509. 89110. 90004. 66062. 75216. 11354. 10312. 90220.
 90262. 90034. 92802.  2151. 92410. 43081. 38018. 60623. 60506. 92129.
 90011. 93230. 11216. 32825. 11213. 12180. 92376. 60050. 78572. 11214.
 97301. 30096. 92509. 19148.  6810. 43055. 70122. 40601. 91786. 91770.
 48858. 97303. 88201. 19131. 92630. 10023. 19380. 10460. 10128. 92404.
 80015. 10033. 11377. 94536. 30093. 93306. 93722. 43701. 60504. 92102.
 27406. 44077. 91977. 30331. 97229. 98037. 44646. 33021. 60644. 60014.
 11374. 19111. 55112. 48103. 97206. 93727. 49509. 91941. 78539. 48843.
 46360. 53081. 61265. 85283. 77055. 89101. 11373. 11208. 10456. 85364.
 10024. 89108. 10027. 95008. 89123. 28205. 94601. 92069. 91789. 84120.
 78550. 80012. 87124. 37211. 21401. 60618. 33177. 92677. 92071. 84084.
 11206. 33157. 28601.   674.   976.   728.   953. 15642. 11420. 93536.
 11215. 80906. 11385. 79936. 95355. 42101. 92104. 75080. 89115. 89119.
 33126. 38111. 92704. 79907. 91352. 65203. 92646. 58103. 97006. 60085.
 90006. 48219. 48203. 11219. 85040. 78666. 90703. 20906. 10009. 75067.
 94538.  6457. 95112. 30022. 63129. 93702. 85009. 11210. 33125. 17602.
 11230. 33176. 47150. 19382. 43229. 75149. 33015. 29223. 76201. 10032.
 91405. 92592. 60477. 93033. 33065. 21222. 78250. 46307. 11201. 10452.
 73505. 28314. 10463.  6460. 60103. 60630. 89502.  7055. 90016. 91335.
 78046. 11756.  7470. 70003. 20002. 44105. 26003. 85705. 90250. 94558.
 60402. 92708. 23456. 88005. 32703. 90044. 95630. 92243. 92557. 11372.
 48234. 91331. 77072. 48221. 11435. 43207. 60632. 37075. 84015. 98115.
 90047. 85201. 60628. 32303. 48601. 63123. 72032. 33025. 44870. 90731.
 92801. 43123. 37922. 92117. 90255. 87112. 15601. 91767. 60441. 92064.
 23454. 63366. 17201. 44118. 61761.  1902. 10028. 75093. 33142. 90018.
 19020.  6010. 95828. 17701. 92626. 75231. 98632. 90650. 89117.  7002.
 93274. 91950. 92879. 45424. 94112. 95376. 29483. 95340. 85710. 93906.
  2301. 85706. 30034. 20011. 94533. 94591.  6516. 21122. 92154. 33614.
 92027. 90026. 90280. 48093. 37042. 49442. 85008. 28540. 77080. 33511.
 96819. 91730. 11211. 60645. 93458. 18901. 47374. 92324. 92647. 38116.
 48235. 75060. 92201.  7060. 94014. 98226. 93720. 60629. 93309. 30043.
 77379. 11355. 10462. 91606. 53209. 94550. 60639. 87505. 94303. 20019.
 23233. 60016. 23462. 33024. 77081. 60636. 35215. 80020.   969.   736.
 60621. 40475. 60544. 30349. 95610. 33063. 78745. 10468. 94086. 99205.
 52001. 93638. 21229. 98208. 11717. 28655. 95687. 95123.  2148. 21207.
   949.  2780.  7728. 98390. 48228. 90744. 11223. 43130. 11225. 75040.
 33311. 11233. 32210. 89014.  7306.    nan]
----------------------------------------------------------------------------------------------------
Department Id
11
[ 2  4  5  3  6  7 10  8  9 11 12]
----------------------------------------------------------------------------------------------------
Latitude
11250
[18.2514534  18.27945137 37.29223251 ... 18.24048233 18.26129723
 18.24248505]
----------------------------------------------------------------------------------------------------
Longitude
4487
[ -66.03705597  -66.0370636  -121.881279   ... -117.8856812   -87.69457245
  -66.54897308]
----------------------------------------------------------------------------------------------------
Order Customer Id
20652
[20755 19492 19491 ... 18579 16244  2677]
----------------------------------------------------------------------------------------------------
Order Id
65752
[77202 75939 75938 ... 26383 26327 26118]
----------------------------------------------------------------------------------------------------
Order Item Cardprod Id
118
[1360  365  627  502  278  249  191  917  828  642  818  825  306  977
   44  251  403  957 1352 1349 1351   60   24  567  893  924  905  564
  885 1363 1353 1357  906  886  926  116  235  273  282  359  565  572
  804  822  835  276  823  203  364 1350  897   37  172  810  821   93
 1347  305 1004 1346   58  311  303 1354 1348   78  258  797  981 1355
  135  134  845  982  625 1359 1356  607 1358 1362  295  127   61   35
  858  860  216   19  226  208  793  792  786  778  777  775  773  771
  768  743  730  728  725  724  715  705  703  691  677  671  666  652
  647  646 1361 1073 1059 1014]
----------------------------------------------------------------------------------------------------
Order Item Discount
1017
[ 13.10999966  16.38999939  18.03000069 ... 140.          33.65999985
  61.18999863]
----------------------------------------------------------------------------------------------------
Order Item Discount Rate
18
[0.04       0.05       0.06       0.07       0.09       0.1
 0.12       0.13       0.15000001 0.16       0.17       0.18000001
 0.2        0.25       0.         0.01       0.02       0.03      ]
----------------------------------------------------------------------------------------------------
Order Item Id
180519
[180517 179254 179253 ...  65129  65126  65113]
----------------------------------------------------------------------------------------------------
Order Item Product Price
75
[ 327.75         59.99000168   39.99000168   50.           44.99000168
   54.97000122   99.98999786   21.98999977   31.98999977   30.
   47.99000168   89.98999786   29.98999977  129.9900055   299.980011
  252.8800049   452.0400085  1500.          999.9899902    79.98999786
   25.           24.98999977   15.98999977  215.8200073   461.480011
  210.8500061    34.99000168   27.98999977   70.           19.98999977
   51.99000168  399.9899902   299.9899902   357.1000061    59.08000183
  199.          399.980011     31.07999992  109.9499969   164.3800049
   11.28999996   94.98999786   17.98999977   99.          532.5800171
   22.          149.9900055   199.9900055    84.40000153  293.0400085
  249.9900055   260.6499939    39.75         99.94999695  329.9899902
  159.9900055   599.9899902   189.          124.9899979  1999.98999
   14.98999977  179.9900055     9.98999977  169.9900055    80.
   65.          108.          100.          119.9899979   209.9900055
  109.9899979   134.9900055    11.53999996  349.9899902    49.97999954]
----------------------------------------------------------------------------------------------------
Order Item Profit Ratio
162
[ 0.28999999 -0.80000001  0.08        0.44999999  0.06        0.33000001
  0.23999999  0.47999999  0.17        0.1         0.05       -0.76999998
  0.28        0.5         0.27000001  0.31        0.46000001  0.30000001
 -0.06        0.09       -0.30000001 -1.33000004  0.2         0.11
  0.19        0.41999999  0.         -0.27000001 -1.54999995  0.34999999
 -0.25        0.25999999 -0.69999999  0.34        0.44        0.49000001
  0.25        0.15000001  0.14       -1.60000002 -0.16        0.16
  0.13        0.04        0.36000001  0.22       -0.1        -0.2
 -0.04        0.37999999 -1.64999998 -0.60000002 -0.05        0.18000001
  0.47       -0.82999998 -0.55000001  0.03       -0.68000001 -0.14
  0.12        0.23        0.07       -1.70000005 -0.19       -0.01
 -0.73000002  0.41       -2.70000005 -0.67000002 -0.20999999 -0.23
  0.20999999 -1.5        -0.23999999 -0.88        0.02        0.37000001
  0.43000001 -1.75       -0.18000001 -0.11        0.31999999 -0.44999999
  0.38999999 -0.17       -0.08       -0.13       -0.74000001 -0.28
 -0.03       -0.09       -1.76999998 -0.63        0.01       -0.22
 -0.15000001 -0.40000001 -0.37999999 -0.33000001 -0.47999999  0.40000001
 -1.42999995 -0.64999998 -0.52999997 -2.75       -1.10000002 -0.07
 -0.62       -0.34       -1.47000003 -2.06999993 -0.85000002 -0.51999998
 -2.5999999  -2.04999995 -2.54999995 -0.63999999 -0.66000003 -2.20000005
 -2.5        -0.37000001 -0.34999999 -0.77999997 -1.57000005 -0.46000001
 -0.75       -0.5        -2.25       -0.43000001 -0.31       -1.29999995
 -0.86000001 -0.36000001 -0.56999999 -1.23000002 -1.04999995 -1.17999995
 -1.25       -0.49000001 -1.79999995 -0.25999999 -0.57999998 -0.31999999
 -0.56       -1.39999998 -0.98000002 -0.44       -2.3499999  -2.6500001
 -0.41999999 -1.20000005 -0.54000002 -0.02       -1.37000001 -2.45000005
 -0.93000001 -1.27999997 -0.89999998 -2.29999995 -1.08000004 -2.0999999 ]
----------------------------------------------------------------------------------------------------
Order Item Quantity
5
[1 2 3 5 4]
----------------------------------------------------------------------------------------------------
Sales
193
[ 327.75        119.9800034    79.98000336  100.           89.98000336
  109.9400024   299.9700012   119.9700012    65.97000122   95.97000122
  179.9700012   150.          250.          199.9499969   239.9499969
  159.9499969   449.9500122   149.9499969   299.9500122   499.9500122
   99.98999786  129.9900055    59.99000168  299.980011    252.8800049
  452.0400085  1500.          999.9899902    79.98999786   44.99000168
  134.9700012    75.           74.97000122   47.97000122  239.9600067
  200.          159.9600067    99.95999908  399.9599915   120.
  215.8200073   461.480011    210.8500061   124.9499969    79.94999695
  224.9499969   174.9499969   139.9499969   140.           50.
   63.97999954   49.97999954   39.97999954   95.98000336  127.9599991
  207.9600067   350.           99.94999695  399.9899902    27.98999977
  299.9899902   357.1000061   125.           79.95999908  179.9600067
  280.           59.08000183   31.97999954  199.9799957    55.97999954
   60.           31.98999977   24.98999977  199.          399.980011
   31.07999992   89.98999786   39.99000168   30.           19.98999977
  109.9499969   164.3800049    11.28999996   63.95999908  191.9600067
  319.9599915   111.9599991   139.9600067   379.9599915    89.94999695
  259.9500122   495.           21.98999977  532.5800171    47.99000168
   15.98999977   51.99000168  103.9800034    43.97999954   69.98000336
   90.          104.9700012    44.           88.           22.
   66.          110.           25.           70.          149.9900055
   34.99000168  199.9900055    17.98999977   84.40000153  293.0400085
  249.9900055   260.6499939   155.9700012   274.8500061    39.75
   29.98999977  399.9500122    71.95999908  219.8800049   299.8500061
  164.9100037    59.97000122  143.9700012   210.           83.97000122
   53.97000122  329.9899902   159.9900055   599.9899902    54.97000122
   59.97999954  199.8999939   284.9700012    89.97000122  119.9599991
   87.95999908  159.9799957    35.97999954  297.          399.7999878
  189.9799957   179.9799957   189.          359.9599915   499.75
  474.9500122   239.9700012   124.9899979  1999.98999     198.
  269.9700012   396.           99.           94.98999786   14.98999977
   29.97999954   59.95999908   44.97000122   74.94999695  179.9900055
   39.95999908   29.96999931   19.97999954    9.98999977   49.95000076
  169.9900055   160.           80.          320.          400.
  240.          325.           65.          130.          195.
  260.          108.          300.          500.          119.9899979
  209.9900055   109.9899979   134.9900055    11.53999996  349.9899902
  149.9400024   249.8999939   199.9199982 ]
----------------------------------------------------------------------------------------------------
Order Item Total
2927
[314.6400146 311.3599854 309.7200012 ... 298.769989  403.7099915
 474.7600098]
----------------------------------------------------------------------------------------------------
Order Profit Per Order
21998
[  91.25      -249.0899963 -247.7799988 ... -103.9700012 -237.5899963
 -337.1000061]
----------------------------------------------------------------------------------------------------
Order Zipcode
609
[   nan 99301. 90049. 94110. 66212. 77041. 85234. 95123. 93727. 85345.
 45231. 47201. 19134. 60016. 60126. 98103. 94601. 10009. 28110. 80219.
 90008. 77095. 32216. 77036. 74133. 94109. 92553. 20735. 60543. 60174.
 31907. 62521. 92627. 28806. 35630.  1852. 10024. 44312. 22153. 89015.
 90045. 10011. 49505. 78664. 76017. 92105. 85705. 90032. 48227. 55407.
 28205. 23602. 94122. 11572. 78207. 68104. 21215. 75081. 10035. 98115.
 49201. 43229. 60653.  6708. 98105. 19143. 42420. 80134. 94533. 92037.
 90036. 22304. 35810. 19711. 38109. 72701. 23223. 40475. 65807. 33801.
 13021. 45503. 78577. 11550. 40214. 67212. 76106. 21044. 30318. 79762.
 60610. 75217. 90004. 89115. 95037. 97206. 14215. 79109. 33614. 75034.
 28540. 32303.  4240. 34952. 63116. 77070.  1841. 97756. 19140. 28314.
 13440. 60623. 95823. 37042. 46060.  8701. 26003. 19120. 19013. 99207.
  2138. 72209. 39212. 44256. 19805. 74012. 23320. 80112. 85023. 38671.
 92374. 62301. 55106. 22801. 47150. 37167. 28403. 29203. 37064. 27604.
 80013. 24153. 43055. 54880. 85281. 92024. 87105. 27893. 75150. 95695.
 33311. 77506. 44240.  4401. 77340.  7960. 35601. 33023. 22204. 37211.
 92704. 30062. 33178. 91104. 60302. 54401. 68025. 33180. 53209. 60505.
 55044. 27707. 75701. 72401. 98661. 48234. 95051. 41042. 46368. 91941.
 74403. 37130. 36608.  7090. 66062. 70506.  7501. 47905. 11561. 33021.
 33142. 80004. 30344. 90301. 43130. 76117. 98042. 98632. 48146. 73120.
 32839. 45373. 92804. 80027. 72032. 79907. 90805.  2908. 55901. 92503.
  1453. 78745. 98052. 84106.  6824. 76706. 60440. 92404. 32712.  2169.
 33024. 98208. 98006. 42104. 85301. 30328. 71203. 32137. 22980. 61032.
 92345. 37620. 97301. 78539. 97477. 92530. 46203. 18103. 75051.  2740.
 12180. 67846. 54601. 43017. 94061.  2149. 37421. 38301. 85204.  3820.
 10550. 89031. 53142. 47374. 44105. 75220. 85323. 54302. 60540. 60025.
 13601. 48183. 44107. 93309. 75023. 87124. 94591. 71111. 30080. 61701.
  7601. 27217. 43615. 93101. 77590.  6457. 60201. 97405. 32503. 98026.
  7060. 33437. 46350. 75061. 30605. 48205. 48126. 17403. 91767. 83605.
 28052. 48601. 19901. 44052. 79424. 10701. 36116. 55113. 23434. 98198.
 13501. 92307. 20016.  8302. 97224.  2038. 61107.  2148. 45014. 90712.
 94086. 75007. 71603. 78041. 46544. 37075. 85254. 28601. 83642. 37918.
 48310. 33012. 85224.  7050. 76021.  6010. 37604. 70601. 92691. 20877.
 88220.  8360. 78501. 27405. 92054. 29501. 92630. 43302. 33458. 33065.
 40324. 28027. 33317. 84107. 39401.  6040. 14609. 98502. 78415. 84041.
 61761. 84084. 94509. 95661. 80020. 84062. 33063.  1915. 10801. 77642.
 90503. 84604. 80906. 32114. 91776. 23464. 85635. 48911. 27834. 77705.

In [15]:
for col in cat_cols:

    print(col)
    print(df[col].nunique())
    print(df[col].unique())
    print('-' * 100)

Type
4
['DEBIT' 'TRANSFER' 'CASH' 'PAYMENT']
----------------------------------------------------------------------------------------------------
Delivery Status
4
['Advance shipping' 'Late delivery' 'Shipping on time' 'Shipping canceled']
----------------------------------------------------------------------------------------------------
Category Name
50
['Sporting Goods' 'Cleats' 'Shop By Sport' "Women's Apparel" 'Electronics'
 'Boxing & MMA' 'Cardio Equipment' 'Trade-In' "Kids' Golf Clubs"
 'Hunting & Shooting' 'Baseball & Softball' "Men's Footwear"
 'Camping & Hiking' 'Consumer Electronics' 'Cameras ' 'Computers'
 'Basketball' 'Soccer' "Girls' Apparel" 'Accessories' "Women's Clothing"
 'Crafts' "Men's Clothing" 'Tennis & Racquet' 'Fitness Accessories'
 'As Seen on  TV!' 'Golf Balls' 'Strength Training' "Children's Clothing"
 'Lacrosse' 'Baby ' 'Fishing' 'Books ' 'DVDs' 'CDs ' 'Garden' 'Hockey'
 'Pet Supplies' 'Health and Beauty' 'Music' 'Video Games' 'Golf Gloves'
 'Golf Bags & Carts' 'Golf Shoes' 'Golf Apparel' "Women's Golf Clubs"
 "Men's Golf Clubs" 'Toys' 'Water Sports' 'Indoor/Outdoor Games']
----------------------------------------------------------------------------------------------------
Customer City
563
['Caguas' 'San Jose' 'Los Angeles' 'Tonawanda' 'Miami' 'San Ramon'
 'Freeport' 'Salinas' 'Peabody' 'Canovanas' 'Paramount' 'Mount Prospect'
 'Long Beach' 'Rancho Cordova' 'Billings' 'Wilkes Barre' 'Roseville'
 'Bellflower' 'Wheaton' 'Detroit' 'Dallas' 'Carlisle' 'Newark'
 'Panorama City' 'Atlanta' 'Fremont' 'Rochester' 'Bayamon' 'Guayama'
 'Juana Diaz' 'Fort Washington' 'Bakersfield' 'Corona' 'Cincinnati'
 'Germantown' 'Carrollton' 'Houston' 'Ewa Beach' 'Lakewood' 'Rome' 'Vista'
 'Fort Worth' 'Fond Du Lac' 'Philadelphia' 'Ontario' 'Oviedo' 'Buffalo'
 'Honolulu' 'Oceanside' 'North Tonawanda' 'Clovis' 'Jamaica'
 'Granite City' 'Medford' 'Pomona' 'Tempe' 'Santa Ana' 'York' 'Aurora'
 'Simi Valley' 'Silver Spring' 'Saint Paul' 'San Antonio' 'Bronx'
 'Greenville' 'Morristown' 'San Diego' 'Oxnard' 'Albuquerque' 'Amarillo'
 'Lutz' 'Bend' 'East Brunswick' 'Lancaster' 'Hampton' 'New York'
 'Porterville' 'Portland' 'Strongsville' 'El Paso' 'Del Rio' 'Bountiful'
 'Kent' 'Chicago' 'Plymouth' 'Far Rockaway' 'Garden Grove' 'Placentia'
 'Mentor' 'Santa Clara' 'Union' 'Westminster' 'Pompano Beach' 'Azusa'
 'Fort Lauderdale' 'Princeton' 'Perth Amboy' 'Loveland' 'Virginia Beach'
 'Louisville' 'Lockport' 'Staten Island' 'Tucson' 'Cleveland' 'Webster'
 'Stockton' 'Martinsburg' 'Cumberland' 'Pekin' 'Tallahassee'
 'Jacksonville' 'Woonsocket' 'Lithonia' 'Oak Lawn' 'Alhambra' 'New Haven'
 'Phoenix' 'Kenner' 'Washington' 'Holland' 'Morrisville' 'Memphis'
 'Federal Way' 'West Covina' 'Ventura' 'Valrico' 'Kaneohe' 'Brooklyn'
 'Lodi' 'Murfreesboro' 'Carlsbad' 'Hamilton' 'Hayward' 'Bridgeton'
 'Bay Shore' 'Palatine' 'Smyrna' 'Van Nuys' 'Opa Locka' 'Edison' 'Baytown'
 'Sylmar' 'Burnsville' 'Huntington Station' 'Sunnyvale' 'Sugar Land'
 'Brighton' 'Bismarck' 'Gaithersburg' 'Lilburn' 'Provo' 'Columbia'
 'Marietta' 'Rio Grande' 'Denver' 'Taylor' 'Saint Charles' 'Cupertino'
 'Springfield' 'Mission Viejo' 'Roswell' 'Ypsilanti' 'Peoria' 'Clementon'
 'Antioch' 'Salt Lake City' 'Granada Hills' 'Hempstead' 'Astoria' 'Gilroy'
 'Lenoir' 'Columbus' 'Albany' 'Humacao' 'Lindenhurst' 'Elyria' 'Riverside'
 'Carson' 'Mesa' 'San Juan' 'Vega Baja' 'Mayaguez' 'Arecibo'
 'San Sebastian' 'Eugene' 'Algonquin' 'Indianapolis' 'Buena Park'
 'Catonsville' 'Jersey City' 'Lombard' 'New Bedford' 'Newburgh' 'Lansdale'
 'Baltimore' 'Fullerton' 'Sacramento' 'Greensboro' 'Roseburg' 'Modesto'
 'Encinitas' 'Watsonville' 'Meridian' 'Endicott' 'Katy' 'Visalia' 'Lompoc'
 'Ogden' 'Raleigh' 'Hacienda Heights' 'Union City' 'Hollywood'
 'Bolingbrook' 'West Lafayette' 'Woodbridge' 'Weslaco' 'Bell Gardens'
 'La Mirada' 'North Bergen' 'Madison' 'South San Francisco'
 'North Las Vegas' 'Methuen' 'Costa Mesa' 'Glen Burnie' 'Fairfield'
 'Winnetka' 'Mcallen' 'Joliet' 'Brownsville' 'Pawtucket'
 'Colorado Springs' 'Quincy' 'Pittsfield' 'Chino' 'Marion' 'North Hills'
 'Salina' 'Hyattsville' 'North Richland Hills' 'Spring Valley' 'Lawrence'
 'Milpitas' 'Rowland Heights' 'Gardena' 'Cicero' 'Asheboro' 'La Crosse'
 'Florissant' 'Canyon Country' 'Ithaca' 'Allentown' 'Escondido' 'Martinez'
 'Troy' 'Arlington' 'Davis' 'Chandler' 'Elgin' 'Palmdale' 'Massapequa'
 'Pittsburg' 'West New York' 'Orlando' 'Hanover' 'Glendale' 'Enfield'
 'Baldwin Park' 'Chino Hills' 'Toms River' 'Wyandotte' 'Mililani' 'Harvey'
 'Mechanicsburg' 'Opelousas' 'Kailua' 'Norfolk' 'Elmhurst' 'Chillicothe'
 'Canoga Park' 'Jackson' 'Moreno Valley' 'New Orleans' 'San Benito'
 'New Castle' 'Bloomfield' 'Cypress' 'Marrero' 'Grand Prairie' 'Greeley'
 'Littleton' 'Longmont' 'Chesapeake' 'Englewood' 'Arlington Heights'
 'Tampa' 'Irvington' 'Forest Hills' 'Dearborn' 'Compton' 'Garland'
 'Waipahu' 'Carmichael' 'Tustin' 'Anaheim' 'Canton' 'Stafford'
 'South Richmond Hill' 'Middletown' 'West Orange' 'Daly City'
 'Powder Springs' 'Parkville' 'Hialeah' 'Beloit' 'Aguadilla' 'Carolina'
 'Yauco' 'Saint Peters' 'Augusta' 'Chapel Hill' 'East Lansing' 'Stamford'
 'Diamond Bar' 'Milwaukee' 'Lawrenceville' 'Manchester' 'La Puente'
 'Victorville' 'Richmond' 'Eagle Pass' 'Fontana' 'Ballwin' 'New Braunfels'
 'Las Vegas' 'Goose Creek' 'Pharr' 'Yonkers' 'El Monte' 'Reynoldsburg'
 'Hamtramck' 'Medina' 'Highland' 'Jonesboro' 'Elk Grove' 'Montebello'
 'San Francisco' 'Glenview' 'Rock Hill' 'Austin' 'Scottsdale' 'Santa Cruz'
 'Oregon City' 'Annandale' 'Plano' 'Piscataway' 'El Cajon' 'Hilliard'
 'Orange Park' 'Decatur' 'San Pablo' 'Douglasville' 'Henderson'
 'College Station' 'Round Rock' 'Mesquite' 'Broken Arrow' 'Redmond'
 'Findlay' 'La Habra' 'Laguna Hills' 'San Bernardino' 'Apex'
 'South El Monte' 'Irving' 'Blacksburg' 'Dorchester Center' 'Potomac'
 'Winter Park' 'Stone Mountain' 'Goleta' 'Hagerstown' 'Alameda'
 'Saint Louis' 'Pico Rivera' 'Chula Vista' 'Hollister' 'North Hollywood'
 'New Brunswick' 'Beaverton' 'Chicago Heights' 'Hesperia' 'Cary' 'Sanford'
 'Laredo' 'Westland' 'Stockbridge' 'Carol Stream' 'Wichita' 'Olathe'
 'Flushing' 'Lynwood' 'Revere' 'Westerville' 'Cordova' 'Hanford' 'Rialto'
 'Mchenry' 'Mission' 'Salem' 'Duluth' 'Danbury' 'Frankfort' 'Upland'
 'Rosemead' 'Mount Pleasant' 'Lake Forest' 'West Chester' 'Woodside'
 'Norcross' 'Fresno' 'Zanesville' 'Painesville' 'Lynnwood' 'Massillon'
 'Crystal Lake' 'Rego Park' 'Ann Arbor' 'Wyoming' 'La Mesa' 'Edinburg'
 'Howell' 'Michigan City' 'Sheboygan' 'Moline' 'Yuma' 'Campbell'
 'Charlotte' 'Oakland' 'San Marcos' 'Walnut' 'Harlingen' 'Rio Rancho'
 'Nashville' 'Annapolis' 'Laguna Niguel' 'Santee' 'West Jordan' 'Hickory'
 'Manati' 'Trujillo Alto' 'Ponce' 'Toa Alta' 'Irwin' 'South Ozone Park'
 'Ridgewood' 'Bowling Green' 'Richardson' 'Sun Valley' 'Huntington Beach'
 'Fargo' 'Waukegan' 'Highland Park' 'Cerritos' 'Lewisville' 'Alpharetta'
 'New Albany' 'Denton' 'Temecula' 'Tinley Park' 'Dundalk' 'Crown Point'
 'Lawton' 'Fayetteville' 'Milford' 'Bartlett' 'Reno' 'Passaic' 'Reseda'
 'Levittown' 'Wayne' 'Metairie' 'Wheeling' 'Hawthorne' 'Napa' 'Berwyn'
 'Fountain Valley' 'Las Cruces' 'Apopka' 'Folsom' 'El Centro'
 'Jackson Heights' 'Pacoima' 'Hendersonville' 'Clearfield' 'Seattle'
 'Saginaw' 'Conway' 'Sandusky' 'San Pedro' 'Grove City' 'Knoxville'
 'Huntington Park' 'Greensburg' 'Poway' 'O Fallon' 'Chambersburg' 'Normal'
 'Lynn' 'Bensalem' 'Bristol' 'Williamsport' 'Longview' 'Norwalk' 'Bayonne'
 'Tulare' 'National City' 'Dayton' 'Tracy' 'Summerville' 'Merced'
 'Brockton' 'Vallejo' 'West Haven' 'Pasadena' 'South Gate' 'Warren'
 'Clarksville' 'Muskegon' 'Brandon' 'Rancho Cucamonga' 'Santa Maria'
 'Doylestown' 'Colton' 'Indio' 'Plainfield' 'Bellingham' 'Spring'
 'Livermore' 'Santa Fe' 'Palo Alto' 'Henrico' 'Des Plaines' 'Birmingham'
 'Broomfield' 'Guaynabo' 'Cayey' 'Citrus Heights' 'Spokane' 'Dubuque'
 'Madera' 'Everett' 'Brentwood' 'Morganton' 'Vacaville' 'Malden'
 'Gwynn Oak' 'Toa Baja' 'Taunton' 'Freehold' 'Sumner' 'Wilmington' 'CA']
----------------------------------------------------------------------------------------------------
Customer Country
2
['Puerto Rico' 'EE. UU.']
----------------------------------------------------------------------------------------------------
Customer Email
1
['XXXXXXXXX']
----------------------------------------------------------------------------------------------------
Customer Fname
782
['Cally' 'Irene' 'Gillian' 'Tana' 'Orli' 'Kimberly' 'Constance' 'Erica'
 'Nichole' 'Oprah' 'Germane' 'Freya' 'Cassandra' 'Natalie' 'Kimberley'
 'Sade' 'Brynne' 'Ciara' 'Bo' 'Kim' 'Kellie' 'Alma' 'Yeo' 'Lucy' 'Simone'
 'Roary' 'Quail' 'Hannah' 'Evelyn' 'Jael' 'Teagan' 'Joan' 'Basia'
 'Dominique' 'Ainsley' 'Aurora' 'Libby' 'Amy' 'Ivory' 'Karina' 'Deanna'
 'Dacey' 'Adele' 'Sybill' 'Kay' 'Stacy' 'Marah' 'Taylor' 'Mary'
 'Elizabeth' 'Katherine' 'Dennis' 'Frances' 'Alice' 'Kyle' 'Brenda'
 'Frank' 'Johnny' 'Austin' 'Michael' 'Vincent' 'Gregory' 'Lisa' 'Megan'
 'Grace' 'Douglas' 'Wayne' 'Ronald' 'Tammy' 'Christina' 'Alexander'
 'Sandra' 'Ruth' 'Lauren' 'Melissa' 'Maria' 'Eugene' 'James' 'John' 'Roy'
 'Janet' 'Nicole' 'Sharon' 'Matthew' 'Anthony' 'Jerry' 'Laura' 'Jack'
 'Kirestin' 'Nora' 'Jennifer' 'Madonna' 'Noelani' 'Sydnee' 'Willa' 'Ila'
 'Belle' 'Alyssa' 'Lani' 'Demetria' 'Gay' 'Audrey' 'Riley' 'Imani'
 'Mechelle' 'Whitney' 'Roanna' 'Vivian' 'Xantha' 'Zia' 'Mara' 'Sloane'
 'Winifred' 'Giselle' 'Nancy' 'David' 'Patricia' 'Julie' 'Tyler' 'Karen'
 'Shawn' 'Willie' 'Bruce' 'Mark' 'Paul' 'Walter' 'Joyce' 'Daniel' 'Pamela'
 'Betty' 'Christian' 'Tiffany' 'Stephen' 'George' 'Samuel' 'Larry' 'Peter'
 'Diana' 'Theresa' 'Cynthia' 'Sean' 'Jonathan' 'Christopher' 'Donald'
 'Rana' 'William' 'Rachel' 'Dorothy' 'Robert' 'Andrea' 'Martha' 'Carolyn'
 'Lynn' 'Julia' 'Patience' 'Cheryl' 'Timothy' 'Aimee' 'Virginia' 'Jessica'
 'Margaret' 'Richard' 'Deborah' 'Emma' 'Adam' 'Sarah' 'Edward' 'Harry'
 'Charles' 'Debra' 'Doris' 'Benjamin' 'Stephanie' 'Nicholas' 'Joseph'
 'Diane' 'Andrew' 'Roger' 'Danielle' 'Patrick' 'Brandon' 'Jacqueline'
 'Kathy' 'Rebecca' 'Jeremy' 'Amanda' 'Felicia' 'Wanda' 'Hayfa' 'Lavinia'
 'Yetta' 'Cleo' 'Wynter' 'Hyacinth' 'Xerxes' 'Noel' 'Maryam' 'Naida'
 'Lana' 'Rylee' 'Dakota' 'Fallon' 'Kylynn' 'Inez' 'Miriam' 'Chloe'
 'Beverly' 'Madeline' 'Yoshi' 'Hadley' 'Renee' 'Iola' 'Tamekah' 'Cherokee'
 'Odessa' 'Rose' 'Linda' 'May' 'Lilah' 'Emi' 'Myra' 'Medge' 'Beatrice'
 'Ria' 'Charity' 'Nell' 'Tamara' 'Phyllis' 'Nelle' 'Blossom' 'Breanna'
 'Katelyn' 'Karly' 'Olga' 'Brenna' 'Tatyana' 'Ifeoma' 'Kitra' 'Summer'
 'Sopoline' 'Eliana' 'Denise' 'Hermione' 'Lara' 'Hedy' 'Violet' 'Clare'
 'Rhonda' 'Morgan' 'Illiana' 'Amity' 'Jayme' 'Geraldine' 'Anika' 'Dana'
 'Sybil' 'Genevieve' 'Tara' 'Ella' 'Heather' 'Brittany' 'Lori' 'Billy'
 'Terry' 'Lawrence' 'Aaron' 'Madison' 'Jane' 'Jordan' 'Kevin' 'Octavia'
 'Emily' 'Kelsie' 'Marie' 'Judy' 'Kenneth' 'Jaime' 'Justin' 'Harold'
 'Ryan' 'Kelly' 'Carl' 'Teresa' 'Nathan' 'Jason' 'Steven' 'Judith' 'Sara'
 'Marilyn' 'Kathryn' 'Ralph' 'Amber' 'Donna' 'Scott' 'Thomas' 'Catherine'
 'Barbara' 'Joshua' 'Susan' 'Zachary' 'Janice' 'Crystal' 'Michelle'
 'Henry' 'Anna' 'Ann' 'Jesse' 'Raymond' 'Audra' 'Cora' 'Hillary' 'Bryan'
 'Gloria' 'Louis' 'Shirley' 'Martina' 'Delilah' 'Jacob' 'Brian' 'Victoria'
 'Jeffrey' 'Helen' 'Gary' 'Ethan' 'Philip' 'Christine' 'Ashley' 'Jean'
 'Eric' 'Hope' 'Unity' 'Blythe' 'Cara' 'Jorden' 'Heidi' 'Lenore' 'Aiko'
 'Kylie' 'Moana' 'Imelda' 'Mariam' 'Rae' 'Jamalia' 'Reagan' 'Amena'
 'Mercedes' 'Brianna' 'Xyla' 'Daria' 'Yvette' 'Ina' 'Fay' 'Destiny'
 'Petra' 'Farrah' 'Clio' 'Leigh' 'Tallulah' 'Pearl' 'Maya' 'Kiayada'
 'Shannon' 'Nayda' 'Charissa' 'Fatima' 'Shelley' 'Yoko' 'Olympia' 'Raya'
 'Quyn' 'Hilary' 'Karyn' 'Germaine' 'Maile' 'Vivien' 'Raven' 'Charlotte'
 'Zelda' 'Isabella' 'Carla' 'Aspen' 'Janna' 'Xena' 'Ocean' 'Hedwig' 'Alea'
 'Aileen' 'Cameron' 'Cailin' 'Jeanette' 'Suki' 'Maxine' 'Sophia' 'Skyler'
 'Yvonne' 'Penelope' 'Tatum' 'Sylvia' 'Amela' 'Keiko' 'Shana' 'Whoopi'
 'Mira' 'Jaden' 'Pascale' 'Maris' 'Cassady' 'Quynn' 'Sage' 'Calista'
 'Sacha' 'Daryl' 'Aphrodite' 'Olivia' 'Mallory' 'Veronica' 'Yuri' 'Joelle'
 'Hiroko' 'Kameko' 'Hollee' 'Eden' 'Lydia' 'Azalia' 'Alika' 'Dahlia'
 'Jenette' 'Paloma' 'Xandra' 'Mariko' 'Darryl' 'Fiona' 'Zephr' 'Uta'
 'Wendy' 'Sierra' 'Kelsey' 'Alexis' 'September' 'McKenzie' 'Eleanor'
 'Chastity' 'Cheyenne' 'Hanna' 'Mona' 'Mari' 'Robin' 'Samantha' 'Gerald'
 'Kyla' 'Xaviera' 'Macy' 'Briar' 'Athena' 'Desirae' 'Maia' 'Carol'
 'Angela' 'Carissa' 'Zena' 'Phillip' 'Bobby' 'Blair' 'Melodie' 'Keith'
 'India' 'Nadine' 'Miranda' 'Piper' 'Charde' 'Russell' 'Isabelle'
 'Mildred' 'Dylan' 'Albert' 'Arthur' 'Kathleen' 'Juan' 'Cathleen' 'Jose'
 'Holly' 'Zenaida' 'Ramona' 'Zorita' 'Jocelyn' 'Alan' 'Mia' 'Justina'
 'Rosalyn' 'Rinah' 'Remedios' 'Shay' 'Aubrey' 'Neve' 'Lacy' 'Leilani'
 'Shelby' 'Stella' 'Camille' 'Carly' 'Teegan' 'Lareina' 'Kirby' 'Kevyn'
 'Gisela' 'Randy' 'Willow' 'Jolie' 'Jade' 'Gwendolyn' 'Lee' 'Celeste'
 'Noelle' 'Brynn' 'Desiree' 'Christen' 'Gemma' 'Kendall' 'Bethany'
 'Callie' 'Ayanna' 'Zoe' 'Brooke' 'Bree' 'Adrienne' 'Nomlanga' 'Sig'
 'Stela' 'Ulla' 'Lesley' 'TaShya' 'Illana' 'Courtney' 'Larissa' 'Juliet'
 'Melyssa' 'Latifah' 'Angelica' 'Eve' 'Melanie' 'Montana' 'Nevada'
 'Abigail' 'Ivy' 'Lacota' 'Stacey' 'Meghan' 'Joe' 'Howard' 'Winter'
 'Jolene' 'Ursa' 'Camilla' 'Iris' 'Bell' 'Chanda' 'Rhiannon' 'Candice'
 'Regan' 'Avye' 'Whilemina' 'Lisandra' 'Guinevere' 'Ivana' 'Velma' 'Rhea'
 'Dora' 'Lael' 'Echo' 'Kyra' 'Rhoda' 'Jana' 'Minerva' 'Jenna' 'Inga'
 'Quemby' 'Abra' 'Quincy' 'Maisie' 'Leila' 'Rossy' 'Charly' 'Iona'
 'Ignacia' 'Marcia' 'Florence' 'Ariel' 'Yen' 'Rowan' 'Halee' 'Nita'
 'Signe' 'Kessie' 'Maggy' 'Aretha' 'Dawn' 'Elaine' 'Meredith' 'Josephine'
 'Maite' 'Anjolie' 'Melinda' 'Kirsten' 'Chelsea' 'Lois' 'Britanney'
 'Jillian' 'Shoshana' 'Bertha' 'Katell' 'Isadora' 'Serina' 'Scarlett'
 'Selma' 'Eugenia' 'Alexa' 'Quintessa' 'Shellie' 'Maggie' 'Caryn'
 'Evangeline' 'Darrel' 'Idola' 'Vielka' 'Clementine' 'Jescie' 'Sydney'
 'Quin' 'Fredericka' 'Chantale' 'Buffy' 'Yael' 'Kai' 'Galena' 'Haviva'
 'Halla' 'April' 'Alfreda' 'Paula' 'Gail' 'Zenia' 'Jessamine' 'Mikayla'
 'Irma' 'Ingrid' 'Chava' 'Laurel' 'Chiquita' 'Marny' 'Faith' 'Amelia'
 'Tashya' 'Tatiana' 'Wynne' 'Karleigh' 'Phoebe' 'Rebekah' 'Regina'
 'Robina' 'Yolanda' 'Glenna' 'Nyssa' 'Kaitlin' 'Vera' 'Sheila' 'Bryar'
 'Ima' 'Haley' 'Kamy' 'Emerald' 'Portia' 'Adara' 'Nerea' 'Harriet' 'Shea'
 'Jemima' 'Lacey' 'Ora' 'Odette' 'Kaye' 'Joanha' 'Leandra' 'Indira'
 'Lunea' 'Keelie' 'Astra' 'Claire' 'Jaquelyn' 'Sonia' 'Kalia' 'Liberty'
 'Anastasia' 'Kiara' 'Ursula' 'Karla' 'Venus' 'Shaine' 'Kerry' 'Susy'
 'Rina' 'Ginger' 'Mike' 'Claudia' 'Pandora' 'Veda' 'Jena' 'Lillian'
 'Deirdre' 'Indigo' 'Lila' 'Hanae' 'Adena' 'Sonya' 'Anne' 'Oliver'
 'Imogene' 'Alexandra' 'Ori' 'Cecilia' 'Lillith' 'Rama' 'Francesca'
 'Hadassah' 'Nola' 'Idona' 'Allegra' 'Shafira' 'Shaeleigh' 'Deme' 'Blaine'
 'Gretchen' 'Madeson' 'Molly' 'Martena' 'Hedda' 'Heidy' 'Filipe' 'Deysi'
 'Brie' 'Alisa' 'Contreras' 'Quon' 'Tasha' 'Lynna' 'Lysandra' 'Priscilla'
 'Britanni' 'Lina' 'Autumn' 'Risa' 'Cami' 'Ana' 'Leslie' 'Nadin' 'Naomi'
 'Ray' 'Larisa' 'Rebeca' 'Jordana' 'Blanca' 'Sybi' 'Mollie' 'BlueOneal'
 'Flora' 'Ariana' 'Anita' 'York' 'Mally' 'Rosa' 'Caro' 'Farley' 'Jenny'
 'Danna' 'Fiora' 'Jay' 'Asley' 'Clau' 'Le' 'Huff' 'Beatty' 'Paola' 'Brees']
----------------------------------------------------------------------------------------------------
Customer Lname
1109
['Holloway' 'Luna' 'Maldonado' ... 'Kiney' 'Delan' 'Harri']
----------------------------------------------------------------------------------------------------
Customer Password
1
['XXXXXXXXX']
----------------------------------------------------------------------------------------------------
Customer Segment
3
['Consumer' 'Home Office' 'Corporate']
----------------------------------------------------------------------------------------------------
Customer State
46
['PR' 'CA' 'NY' 'FL' 'MA' 'IL' 'MT' 'PA' 'MI' 'TX' 'DE' 'GA' 'MD' 'OH'
 'HI' 'NJ' 'WI' 'AZ' 'CO' 'MN' 'NC' 'NM' 'OR' 'SC' 'VA' 'UT' 'WA' 'KY'
 'WV' 'RI' 'CT' 'LA' 'TN' 'DC' 'ND' 'MO' 'IN' 'ID' 'NV' 'KS' 'AR' 'OK'
 'AL' 'IA' '95758' '91732']
----------------------------------------------------------------------------------------------------
Customer Street
7458
['5365 Noble Nectar Island' '2679 Rustic Loop' '8510 Round Bear Gate' ...
 '245 Lost Way ' '2455 Merry Hollow ' '8621 Broad Forest ']
----------------------------------------------------------------------------------------------------
Department Name
11
['Fitness' 'Apparel' 'Golf' 'Footwear' 'Outdoors' 'Fan Shop' 'Technology'
 'Book Shop' 'Discs Shop' 'Pet Shop' 'Health and Beauty ']
----------------------------------------------------------------------------------------------------
Market
5
['Pacific Asia' 'USCA' 'Africa' 'Europe' 'LATAM']
----------------------------------------------------------------------------------------------------
Order City
3597
['Bekasi' 'Bikaner' 'Townsville' ... 'Tongling' 'Liuyang' 'Nashua']
----------------------------------------------------------------------------------------------------
Order Country
164
['Indonesia' 'India' 'Australia' 'China' 'Japón' 'Corea del Sur'
 'Singapur' 'Turquía' 'Mongolia' 'Estados Unidos' 'Nigeria'
 'República Democrática del Congo' 'Senegal' 'Marruecos' 'Alemania'
 'Francia' 'Países Bajos' 'Reino Unido' 'Guatemala' 'El Salvador' 'Panamá'
 'República Dominicana' 'Venezuela' 'Colombia' 'Honduras' 'Brasil'
 'México' 'Uruguay' 'Argentina' 'Cuba' 'Perú' 'Nicaragua' 'Ecuador'
 'Angola' 'Sudán' 'Somalia' 'Costa de Marfil' 'Egipto' 'Italia' 'España'
 'Suecia' 'Austria' 'Canada' 'Madagascar' 'Argelia' 'Liberia' 'Zambia'
 'Níger' 'SudAfrica' 'Mozambique' 'Tanzania' 'Ruanda' 'Israel'
 'Nueva Zelanda' 'Bangladés' 'Tailandia' 'Irak' 'Arabia Saudí' 'Filipinas'
 'Kazajistán' 'Irán' 'Myanmar (Birmania)' 'Uzbekistán' 'Benín' 'Camerún'
 'Kenia' 'Togo' 'Ucrania' 'Polonia' 'Portugal' 'Rumania'
 'Trinidad y Tobago' 'Afganistán' 'Pakistán' 'Vietnam' 'Malasia'
 'Finlandia' 'Rusia' 'Irlanda' 'Noruega' 'Eslovaquia' 'Bélgica' 'Bolivia'
 'Chile' 'Jamaica' 'Yemen' 'Ghana' 'Guinea' 'Etiopía' 'Bulgaria'
 'Kirguistán' 'Georgia' 'Nepal' 'Emiratos Árabes Unidos' 'Camboya'
 'Uganda' 'Lesoto' 'Lituania' 'Suiza' 'Hungría' 'Dinamarca' 'Haití'
 'Bielorrusia' 'Croacia' 'Laos' 'Baréin' 'Macedonia' 'República Checa'
 'Sri Lanka' 'Zimbabue' 'Eritrea' 'Burkina Faso' 'Costa Rica' 'Libia'
 'Barbados' 'Tayikistán' 'Siria' 'Guadalupe' 'Papúa Nueva Guinea'
 'Azerbaiyán' 'Turkmenistán' 'Paraguay' 'Jordania' 'Hong Kong' 'Martinica'
 'Moldavia' 'Qatar' 'Mali' 'Albania' 'República del Congo'
 'Bosnia y Herzegovina' 'Omán' 'Túnez' 'Sierra Leona' 'Yibuti' 'Burundi'
 'Montenegro' 'Gabón' 'Sudán del Sur' 'Luxemburgo' 'Namibia' 'Mauritania'
 'Grecia' 'Suazilandia' 'Guyana' 'Guayana Francesa'
 'República Centroafricana' 'Taiwán' 'Estonia' 'Líbano' 'Chipre'
 'Guinea-Bissau' 'Surinam' 'Belice' 'Eslovenia' 'República de Gambia'
 'Botsuana' 'Armenia' 'Guinea Ecuatorial' 'Kuwait' 'Bután' 'Chad' 'Serbia'
 'Sáhara Occidental']
----------------------------------------------------------------------------------------------------
order date (DateOrders)
65752
['1/31/2018 22:56' '1/13/2018 12:27' '1/13/2018 12:06' ...
 '1/21/2016 2:47' '1/20/2016 7:10' '1/17/2016 5:56']
----------------------------------------------------------------------------------------------------
Order Region
23
['Southeast Asia' 'South Asia' 'Oceania' 'Eastern Asia' 'West Asia'
 'West of USA ' 'US Center ' 'West Africa' 'Central Africa' 'North Africa'
 'Western Europe' 'Northern Europe' 'Central America' 'Caribbean'
 'South America' 'East Africa' 'Southern Europe' 'East of USA' 'Canada'
 'Southern Africa' 'Central Asia' 'Eastern Europe' 'South of  USA ']
----------------------------------------------------------------------------------------------------
Order State
1089
['Java Occidental' 'Rajastán' 'Queensland' ... 'Bistrita-Nasaud' 'Tottori'
 'Khorezm']

In [16]:
df['Customer Zipcode'].reset_index()

         index  Customer Zipcode
0            0             725.0
1            1             725.0
2            2           95125.0
3            3           90027.0
4            4             725.0
...        ...               ...
180514  180514           11207.0
180515  180515           93304.0
180516  180516            6010.0
180517  180517             725.0
180518  180518             725.0

[180519 rows x 2 columns]

## Data Cleaning (if any)

### Dropping Fake Data

In [17]:
df.drop(['Customer Zipcode','Customer Email','Product Image','Customer Email','Customer Password'],axis=1,inplace=True)

In [18]:
### drop these columns as uselees Customer Country,Customer Email,Customer Password, Customer State,Customer Street,Product Image,Order Region

### Getting Insights from the data

Checking the highest sales per each country

In [19]:
df.groupby('Customer Country')['Sales per customer'].sum().sort_values(ascending=False).head(10).reset_index()

  Customer Country  Sales per customer
0          EE. UU.        2.034315e+07
1      Puerto Rico        1.271125e+07

In [20]:
df.groupby(['Order Country', 'Order City'])['Sales'].sum().sort_values(ascending=False).reset_index().round(10).head(30)

           Order Country      Order City          Sales
0         Estados Unidos   New York City  436061.538159
1   República Dominicana   Santo Domingo  432351.878303
2         Estados Unidos     Los Angeles  370545.137497
3               Honduras     Tegucigalpa  364129.987113
4              Nicaragua         Managua  335424.756486
5                 México     Mexico City  298471.835883
6              Filipinas          Manila  271819.805030
7         Estados Unidos   San Francisco  256245.625345
8         Estados Unidos    Philadelphia  255914.244948
9            Reino Unido          London  240922.264373
10           El Salvador    San Salvador  224552.114408
11              Alemania          Berlín  222748.703818
12               Austria           Viena  222211.964032
13        Estados Unidos         Seattle  206658.243978
14             Indonesia         Yakarta  205532.434009
15             Argentina    Buenos Aires  193330.243582
16             Tailandia         Bangkok  185935.213563
17               Nigeria           Lagos  183586.433348
18              Honduras  San Pedro Sula  181720.773626
19               Francia           Paris  179632.283125
20                España          Madrid  179042.153015
21        Estados Unidos         Houston  174961.623578
22             Australia          Sydney  163661.713264
23                Panamá     Panama City  163352.893076
24                Brasil       São Paulo  159056.183100
25             Guatemala           Mixco  155163.102880
26        Estados Unidos         Chicago  154542.253189
27               Turquía        Estambul  147105.472942
28             Australia       Melbourne  146329.542998
29              Alemania        Hamburgo  137038.102602

In [21]:
df_us=df[df['Order Country']=='Estados Unidos']
plot=df_us.groupby('Order City')['Sales'].sum().sort_values(ascending=False).reset_index().round(2).head(20)
plot

       Order City      Sales
0   New York City  436061.54
1     Los Angeles  370545.14
2   San Francisco  256245.63
3    Philadelphia  255914.24
4         Seattle  206658.24
5         Houston  174961.62
6         Chicago  154542.25
7        Columbus  112520.61
8       San Diego   87113.19
9     Springfield   72781.07
10         Dallas   70714.72
11   Jacksonville   55778.40
12        Detroit   53520.60
13         Newark   47678.56
14       Columbia   45364.42
15       Richmond   43367.65
16    San Antonio   37148.78
17         Aurora   32518.91
18        Phoenix   31867.02
19        Jackson   30959.08

In [22]:
px.pie(data_frame=plot, values='Sales', names='Order City', title='Sales by City in the US')

In [23]:
### Decision to Form a depot in the north east region of the US is based on the sales data. The top 15 cities in the US with the highest sales are: New York City

In [24]:
northeast_total=df_us[df_us['Order City'].isin(['New York City','Philadelphia','Newark','Richmond'])]['Sales'].sum()

print(f"Total Sales for Northeast Cluster   : ${northeast_total:,.2f}")

Total Sales for Northeast Cluster   : $783,022.00

In [25]:
western_total=df_us[df_us['Order City'].isin(['Los Angeles','San Francisco','San Diego'])]['Sales'].sum()

print(f"Total Sales for Western Cluster     : ${western_total:,.2f}")

Total Sales for Western Cluster     : $713,903.95

In [1]:
### Exploring the data to find another perspective on the data of the late delivery risk

In [ ]:
plot_x=df_us.groupby('Order City')['Late_delivery_risk'].count().sort_values(ascending=False).reset_index().head(21)
plot_x

       Order City  Late_delivery_risk
0   New York City                2202
1     Los Angeles                1845
2    Philadelphia                1302
3   San Francisco                1297
4         Seattle                1066
5         Houston                 875
6         Chicago                 789
7        Columbus                 550
8       San Diego                 425
9     Springfield                 379
10         Dallas                 374
11   Jacksonville                 277
12        Detroit                 276
13         Newark                 244
14       Richmond                 227
15       Columbia                 226
16    San Antonio                 187
17         Aurora                 175
18        Jackson                 169
19     Louisville                 168
20        Phoenix                 157

In [ ]:
px.bar(data_frame=plot_x, x='Order City', y='Late_delivery_risk', title='Late Delivery Risk per each City in the US')

In [ ]:
df.groupby(['Order Country','Customer Country','Customer City'])['Sales'].sum().sort_values(ascending=False).reset_index().round(20)

        Order Country Customer Country Customer City         Sales
0      Estados Unidos      Puerto Rico        Caguas  1.802379e+06
1             Francia      Puerto Rico        Caguas  1.102674e+06
2              México      Puerto Rico        Caguas  9.777614e+05
3            Alemania      Puerto Rico        Caguas  7.813826e+05
4           Australia      Puerto Rico        Caguas  6.183036e+05
...               ...              ...           ...           ...
15820           China          EE. UU.  Crystal Lake  1.129000e+01
15821           Japón          EE. UU.       Houston  1.129000e+01
15822           China          EE. UU.   Chino Hills  1.129000e+01
15823          España          EE. UU.       Modesto  1.129000e+01
15824           India          EE. UU.   Tinley Park  1.129000e+01

[15825 rows x 4 columns]

In [ ]:
real_top_buyers = df.groupby(['Customer Id', 'Customer Fname', 'Customer Lname','Order Country','Customer City','Order City'])['Sales per customer'].sum().sort_values(ascending=False).round(3).reset_index()
real_top_buyers

,Customer Id,Customer Fname,Customer Lname,Order Country,Customer City,Order City,Sales per customer
0,9515,Victoria,Smith,Reino Unido,Caguas,Colchester,2768.41
1,10744,Samantha,Smith,España,Palatine,Sant Boi de Llobregat,2668.11
2,5946,Daniel,Smith,Italia,Caguas,Genoa,2517.07
3,9490,Mary,Glass,Indonesia,La Mesa,Yakarta,2467.51
4,1148,Mary,Anderson,Francia,Augusta,Marseille,2428.29
...,...,...,...,...,...,...,...
65490,12941,Lavinia,Wilkerson,Francia,Scottsdale,Le Mans,8.47
65491,17785,Cassandra,Camacho,Filipinas,Longmont,Manila,8.47
65492,17875,Shay,Welch,Indonesia,Aurora,Bandung,8.47
65493,4220,Mary,Morgan,China,Caguas,Mianyang,7.99
65494,2712,Mary,Castillo,Honduras,Fremont,El Progreso,7.49

In [ ]:
real_top_buyers_count = df.groupby(['Customer Id', 'Customer Fname', 'Customer Lname','Order Country'])['Sales per customer'].count().sort_values(ascending=False).head(10).reset_index()
real_top_buyers_count

,Customer Id,Customer Fname,Customer Lname,Order Country,Sales per customer
0,11430,Mary,Miller,Estados Unidos,24
1,10198,Mary,Smith,Estados Unidos,19
2,11039,Mary,Torres,Estados Unidos,18
3,5417,Dennis,Meyer,Estados Unidos,18
4,5640,Matthew,Smith,Estados Unidos,17
5,731,Robert,Smith,Estados Unidos,17
6,6279,Gary,Lewis,Estados Unidos,17
7,11768,Virginia,Smith,Estados Unidos,17
8,5654,Jerry,Smith,Estados Unidos,17
9,11132,Jonathan,Washington,Estados Unidos,17

In [ ]:
df['Customer Fname']

0           Cally
1           Irene
2         Gillian
3            Tana
4            Orli
           ...
180514      Maria
180515     Ronald
180516       John
180517       Mary
180518     Andrea
Name: Customer Fname, Length: 180519, dtype: object

In [ ]:
df[df['Customer Lname'].isna()]

,Type,Days for shipping (real),Days for shipment (scheduled),Benefit per order,Sales per customer,Delivery Status,Late_delivery_risk,Category Id,Category Name,Customer City,...,Order State,Order Status,Product Card Id,Product Category Id,Product Image,Product Name,Product Price,Product Status,shipping date (DateOrders),Shipping Mode
41422,DEBIT,5,4,165.360001,337.459992,Late delivery,1,63,Children's Clothing,Caguas,...,Java Central,COMPLETE,1350,63,http://images.acmesports.sports/Children+heaters,Children's heaters,357.100006,0,12/26/2017 19:40,Standard Class
50447,DEBIT,2,4,213.690002,436.100006,Advance shipping,0,66,Crafts,Palatine,...,Estocolmo,COMPLETE,1353,66,http://images.acmesports.sports/Porcelain+crafts,Porcelain crafts,461.480011,0,11/9/2017 14:50,Standard Class
86260,TRANSFER,5,4,152.440002,419.950012,Late delivery,1,66,Crafts,Los Angeles,...,Guangdong,PENDING,1353,66,http://images.acmesports.sports/Porcelain+crafts,Porcelain crafts,461.480011,0,1/1/2018 19:19,Standard Class
92621,TRANSFER,2,1,-4.860000,194.240005,Late delivery,1,76,Women's Clothing,Caguas,...,Capital Nacional,PENDING,1363,76,http://images.acmesports.sports/Summer+dresses,Summer dresses,215.820007,0,12/15/2017 7:25,First Class
97530,DEBIT,4,2,82.540001,242.759995,Late delivery,1,65,Consumer Electronics,San Antonio,...,Lombardía,ON_HOLD,1352,65,http://images.acmesports.sports/Industrial+con...,Industrial consumer electronics,252.880005,0,11/4/2017 20:37,Second Class
120404,TRANSFER,3,4,157.830002,415.329987,Advance shipping,0,66,Crafts,Fayetteville,...,Renania del Norte-Westfalia,PENDING,1353,66,http://images.acmesports.sports/Porcelain+crafts,Porcelain crafts,461.480011,0,11/10/2017 1:10,Standard Class
166129,PAYMENT,2,2,-59.279999,296.390015,Shipping on time,0,63,Children's Clothing,Honolulu,...,Java Oriental,PENDING_PAYMENT,1350,63,http://images.acmesports.sports/Children+heaters,Children's heaters,357.100006,0,12/23/2017 16:52,Second Class
167119,PAYMENT,2,4,15.050000,200.710007,Advance shipping,0,76,Women's Clothing,Reseda,...,Uttar Pradesh,PENDING_PAYMENT,1363,76,http://images.acmesports.sports/Summer+dresses,Summer dresses,215.820007,0,1/29/2018 8:14,Standard Class

In [ ]:
print(df[df['Customer Lname'].isna()][['Customer Fname', 'Customer Lname', 'Customer City']])

       Customer Fname Customer Lname Customer City
41422             May            NaN        Caguas
50447       Contreras            NaN      Palatine
86260             Ray            NaN   Los Angeles
92621       BlueOneal            NaN        Caguas
97530            York            NaN   San Antonio
120404         Farley            NaN  Fayetteville
166129             Le            NaN      Honolulu
167119           Huff            NaN        Reseda

In [ ]:
df['Customer Lname'] = df['Customer Lname'].fillna('Unknown')

In [ ]:
print(df[['Customer Fname', 'Customer Lname', 'Customer City','Customer Country']])

       Customer Fname Customer Lname Customer City Customer Country
0               Cally       Holloway        Caguas      Puerto Rico
1               Irene           Luna        Caguas      Puerto Rico
2             Gillian      Maldonado      San Jose          EE. UU.
3                Tana           Tate   Los Angeles          EE. UU.
4                Orli      Hendricks        Caguas      Puerto Rico
...               ...            ...           ...              ...
180514          Maria       Peterson      Brooklyn          EE. UU.
180515         Ronald          Clark   Bakersfield          EE. UU.
180516           John          Smith       Bristol          EE. UU.
180517           Mary          Smith        Caguas      Puerto Rico
180518         Andrea         Ortega        Caguas      Puerto Rico

[180519 rows x 4 columns]

In [ ]:
df.groupby(['Category Name','Customer City'])['Sales per customer'].sum().sort_values(ascending=False).reset_index().round(3)

          Category Name        Customer City  Sales per customer
0               Fishing               Caguas         2306699.214
1                Cleats               Caguas         1472880.039
2      Camping & Hiking               Caguas         1340660.512
3      Cardio Equipment               Caguas         1223170.462
4       Women's Apparel               Caguas         1049018.750
...                 ...                  ...                 ...
12709              CDs            Cumberland               8.470
12710              CDs   South San Francisco               8.470
12711              CDs            Scottsdale               8.470
12712              CDs              Longmont               8.470
12713       Golf Gloves             Alhambra               8.390

[12714 rows x 3 columns]

### check the correlation between shipping cost & country

#### Check the sales trend over time

In [ ]:
import datetime

datetime.datetime.today()

datetime.datetime(2026, 10, 6, 21, 50, 24, 95075)

In [ ]:
df['order_date_formatted'] = pd.to_datetime(df['order date (DateOrders)'])

In [ ]:
df['order_date_formatted'].describe()

count                           180519
mean     2016-06-12 17:47:04.669868544
min                2015-01-01 00:00:00
25%                2015-09-21 13:49:00
50%                2016-06-11 13:06:00
75%                2017-03-01 08:42:00
max                2018-01-31 23:38:00
Name: order_date_formatted, dtype: object

In [ ]:
df['order_year'] = df['order_date_formatted'].dt.year
df['order_year']

0         2018
1         2018
2         2018
3         2018
4         2018
          ...
180514    2016
180515    2016
180516    2016
180517    2016
180518    2016
Name: order_year, Length: 180519, dtype: int32

In [ ]:
df_sorted = df.sort_values(by= 'order_year')
df_sorted

,Type,Days for shipping (real),Days for shipment (scheduled),Benefit per order,Sales per customer,Delivery Status,Late_delivery_risk,Category Id,Category Name,Customer City,...,Product Description,Product Name,Product Price,Product Status,shipping date (DateOrders),Shipping Mode,order date,order_date formatted,order_date_formatted,order_year
62700,CASH,2,1,87.290001,193.979996,Late delivery,1,9,Cardio Equipment,Portland,...,NaN,Nike Men's Free 5.0+ Running Shoe,99.989998,0,2/11/2015 10:37,First Class,2015-02-09 10:37:00,2015-02-09 10:37:00,2015-02-09 10:37:00,2015
62699,CASH,2,1,-13.460000,80.620003,Late delivery,1,37,Electronics,Baltimore,...,NaN,Titleist Pro V1x Golf Balls,47.990002,0,8/6/2015 22:59,First Class,2015-08-04 22:59:00,2015-08-04 22:59:00,2015-08-04 22:59:00,2015
62694,CASH,2,1,27.709999,79.180000,Late delivery,1,29,Shop By Sport,Houston,...,NaN,Under Armour Girls' Toddler Spine Surge Runni,39.990002,0,10/21/2015 16:56,First Class,2015-10-19 16:56:00,2015-10-19 16:56:00,2015-10-19 16:56:00,2015
62692,CASH,2,1,36.029999,109.180000,Late delivery,1,17,Cleats,Crystal Lake,...,NaN,Perfect Fitness Perfect Rip Deck,59.990002,0,10/15/2015 17:38,First Class,2015-10-13 17:38:00,2015-10-13 17:38:00,2015-10-13 17:38:00,2015
62718,CASH,2,1,-191.080002,272.970001,Late delivery,1,9,Cardio Equipment,San Diego,...,NaN,Nike Men's Free 5.0+ Running Shoe,99.989998,0,9/21/2015 22:13,First Class,2015-09-19 22:13:00,2015-09-19 22:13:00,2015-09-19 22:13:00,2015
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
158007,TRANSFER,3,2,12.020000,33.389999,Late delivery,1,75,Video Games,Caguas,...,NaN,Fighting video games,39.750000,0,1/23/2018 8:25,Second Class,2018-01-20 08:25:00,2018-01-20 08:25:00,2018-01-20 08:25:00,2018
158006,TRANSFER,2,2,8.680000,33.389999,Shipping on time,0,75,Video Games,Caguas,...,NaN,Fighting video games,39.750000,0,1/20/2018 12:16,Second Class,2018-01-18 12:16:00,2018-01-18 12:16:00,2018-01-18 12:16:00,2018
158005,TRANSFER,3,2,-94.410004,37.759998,Late delivery,1,75,Video Games,Caguas,...,NaN,Fighting video games,39.750000,0,1/23/2018 4:55,Second Class,2018-01-20 04:55:00,2018-01-20 04:55:00,2018-01-20 04:55:00,2018
158004,TRANSFER,4,2,93.669998,258.040008,Late delivery,1,71,Music,Caguas,...,NaN,Rock music,260.649994,0,1/9/2018 0:54,Second Class,2018-01-05 00:54:00,2018-01-05 00:54:00,2018-01-05 00:54:00,2018
158014,TRANSFER,3,2,56.110001,215.820007,Late delivery,1,76,Women's Clothing,Caguas,...,NaN,Summer dresses,215.820007,0,2/2/2018 20:40,Second Class,2018-01-30 20:40:00,2018-01-30 20:40:00,2018-01-30 20:40:00,2018

In [ ]:
plot_df = df_sorted.groupby('order_year')['Sales'].sum().reset_index()
plot_df

   order_year         Sales
0        2015  1.234083e+07
1        2016  1.230382e+07
2        2017  1.180844e+07
3        2018  3.316501e+05

In [ ]:
px.line(data_frame= plot_df, x= 'order_date_formatted', y= 'Sales')

In [ ]:
px.line(data_frame= plot_df, x= 'order_year', y= 'Sales',title='Sales trend over the year')

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 180519 entries, 0 to 180518
Data columns (total 52 columns):
 #   Column                         Non-Null Count   Dtype
---  ------                         --------------   -----
 0   Type                           180519 non-null  object
 1   Days for shipping (real)       180519 non-null  int64
 2   Days for shipment (scheduled)  180519 non-null  int64
 3   Benefit per order              180519 non-null  float64
 4   Sales per customer             180519 non-null  float64
 5   Delivery Status                180519 non-null  object
 6   Late_delivery_risk             180519 non-null  int64
 7   Category Id                    180519 non-null  int64
 8   Category Name                  180519 non-null  object
 9   Customer City                  180519 non-null  object
 10  Customer Country               180519 non-null  object
 11  Customer Fname                 180519 non-null  object
 12  Customer Id                    180519 non-null  int64
 13  Customer Lname                 180511 non-null  object
 14  Customer Segment               180519 non-null  object
 15  Customer State                 180519 non-null  object
 16  Customer Street                180519 non-null  object
 17  Department Id                  180519 non-null  int64
 18  Department Name                180519 non-null  object
 19  Latitude                       180519 non-null  float64
 20  Longitude                      180519 non-null  float64
 21  Market                         180519 non-null  object
 22  Order City                     180519 non-null  object
 23  Order Country                  180519 non-null  object
 24  Order Customer Id              180519 non-null  int64
 25  order date (DateOrders)        180519 non-null  datetime64[ns]
 26  Order Id                       180519 non-null  int64
 27  Order Item Cardprod Id         180519 non-null  int64
 28  Order Item Discount            180519 non-null  float64
 29  Order Item Discount Rate       180519 non-null  float64
 30  Order Item Id                  180519 non-null  int64
 31  Order Item Product Price       180519 non-null  float64
 32  Order Item Profit Ratio        180519 non-null  float64
 33  Order Item Quantity            180519 non-null  int64
 34  Sales                          180519 non-null  float64
 35  Order Item Total               180519 non-null  float64
 36  Order Profit Per Order         180519 non-null  float64
 37  Order Region                   180519 non-null  object
 38  Order State                    180519 non-null  object
 39  Order Status                   180519 non-null  object
 40  Product Card Id                180519 non-null  int64
 41  Product Category Id            180519 non-null  int64
 42  Product Description            0 non-null       float64
 43  Product Name                   180519 non-null  object
 44  Product Price                  180519 non-null  float64
 45  Product Status                 180519 non-null  int64
 46  shipping date (DateOrders)     180519 non-null  object
 47  Shipping Mode                  180519 non-null  object
 48  order date                     180519 non-null  datetime64[ns]
 49  order_date formatted           180519 non-null  datetime64[ns]
 50  order_date_formatted           180519 non-null  datetime64[ns]
 51  order_year                     180519 non-null  int32
dtypes: datetime64[ns](4), float64(13), int32(1), int64(14), object(20)
memory usage: 70.9+ MB

In [ ]:
df.to_parquet('cleaned_data.parquet')

In [ ]:
df_3 = pd.read_parquet('cleaned_data.parquet')
df_3

,Type,Days for shipping (real),Days for shipment (scheduled),Benefit per order,Sales per customer,Delivery Status,Late_delivery_risk,Category Id,Category Name,Customer City,...,Product Description,Product Name,Product Price,Product Status,shipping date (DateOrders),Shipping Mode,order date,order_date formatted,order_date_formatted,order_year
0,DEBIT,3,4,91.250000,314.640015,Advance shipping,0,73,Sporting Goods,Caguas,...,NaN,Smart watch,327.750000,0,2/3/2018 22:56,Standard Class,2018-01-31 22:56:00,2018-01-31 22:56:00,2018-01-31 22:56:00,2018
1,TRANSFER,5,4,-249.089996,311.359985,Late delivery,1,73,Sporting Goods,Caguas,...,NaN,Smart watch,327.750000,0,1/18/2018 12:27,Standard Class,2018-01-13 12:27:00,2018-01-13 12:27:00,2018-01-13 12:27:00,2018
2,CASH,4,4,-247.779999,309.720001,Shipping on time,0,73,Sporting Goods,San Jose,...,NaN,Smart watch,327.750000,0,1/17/2018 12:06,Standard Class,2018-01-13 12:06:00,2018-01-13 12:06:00,2018-01-13 12:06:00,2018
3,DEBIT,3,4,22.860001,304.809998,Advance shipping,0,73,Sporting Goods,Los Angeles,...,NaN,Smart watch,327.750000,0,1/16/2018 11:45,Standard Class,2018-01-13 11:45:00,2018-01-13 11:45:00,2018-01-13 11:45:00,2018
4,PAYMENT,2,4,134.210007,298.250000,Advance shipping,0,73,Sporting Goods,Caguas,...,NaN,Smart watch,327.750000,0,1/15/2018 11:24,Standard Class,2018-01-13 11:24:00,2018-01-13 11:24:00,2018-01-13 11:24:00,2018
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
180514,CASH,4,4,40.000000,399.980011,Shipping on time,0,45,Fishing,Brooklyn,...,NaN,Field & Stream Sportsman 16 Gun Fire Safe,399.980011,0,1/20/2016 3:40,Standard Class,2016-01-16 03:40:00,2016-01-16 03:40:00,2016-01-16 03:40:00,2016
180515,DEBIT,3,2,-613.770019,395.980011,Late delivery,1,45,Fishing,Bakersfield,...,NaN,Field & Stream Sportsman 16 Gun Fire Safe,399.980011,0,1/19/2016 1:34,Second Class,2016-01-16 01:34:00,2016-01-16 01:34:00,2016-01-16 01:34:00,2016
180516,TRANSFER,5,4,141.110001,391.980011,Late delivery,1,45,Fishing,Bristol,...,NaN,Field & Stream Sportsman 16 Gun Fire Safe,399.980011,0,1/20/2016 21:00,Standard Class,2016-01-15 21:00:00,2016-01-15 21:00:00,2016-01-15 21:00:00,2016
180517,PAYMENT,3,4,186.229996,387.980011,Advance shipping,0,45,Fishing,Caguas,...,NaN,Field & Stream Sportsman 16 Gun Fire Safe,399.980011,0,1/18/2016 20:18,Standard Class,2016-01-15 20:18:00,2016-01-15 20:18:00,2016-01-15 20:18:00,2016
180518,PAYMENT,4,4,168.949997,383.980011,Shipping on time,0,45,Fishing,Caguas,...,NaN,Field & Stream Sportsman 16 Gun Fire Safe,399.980011,0,1/19/2016 18:54,Standard Class,2016-01-15 18:54:00,2016-01-15 18:54:00,2016-01-15 18:54:00,2016

In [ ]:
df_3.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 180519 entries, 0 to 180518
Data columns (total 52 columns):
 #   Column                         Non-Null Count   Dtype
---  ------                         --------------   -----
 0   Type                           180519 non-null  object
 1   Days for shipping (real)       180519 non-null  int64
 2   Days for shipment (scheduled)  180519 non-null  int64
 3   Benefit per order              180519 non-null  float64
 4   Sales per customer             180519 non-null  float64
 5   Delivery Status                180519 non-null  object
 6   Late_delivery_risk             180519 non-null  int64
 7   Category Id                    180519 non-null  int64
 8   Category Name                  180519 non-null  object
 9   Customer City                  180519 non-null  object
 10  Customer Country               180519 non-null  object
 11  Customer Fname                 180519 non-null  object
 12  Customer Id                    180519 non-null  int64
 13  Customer Lname                 180511 non-null  object
 14  Customer Segment               180519 non-null  object
 15  Customer State                 180519 non-null  object
 16  Customer Street                180519 non-null  object
 17  Department Id                  180519 non-null  int64
 18  Department Name                180519 non-null  object
 19  Latitude                       180519 non-null  float64
 20  Longitude                      180519 non-null  float64
 21  Market                         180519 non-null  object
 22  Order City                     180519 non-null  object
 23  Order Country                  180519 non-null  object
 24  Order Customer Id              180519 non-null  int64
 25  order date (DateOrders)        180519 non-null  datetime64[ns]
 26  Order Id                       180519 non-null  int64
 27  Order Item Cardprod Id         180519 non-null  int64
 28  Order Item Discount            180519 non-null  float64
 29  Order Item Discount Rate       180519 non-null  float64
 30  Order Item Id                  180519 non-null  int64
 31  Order Item Product Price       180519 non-null  float64
 32  Order Item Profit Ratio        180519 non-null  float64
 33  Order Item Quantity            180519 non-null  int64
 34  Sales                          180519 non-null  float64
 35  Order Item Total               180519 non-null  float64
 36  Order Profit Per Order         180519 non-null  float64
 37  Order Region                   180519 non-null  object
 38  Order State                    180519 non-null  object
 39  Order Status                   180519 non-null  object
 40  Product Card Id                180519 non-null  int64
 41  Product Category Id            180519 non-null  int64
 42  Product Description            0 non-null       float64
 43  Product Name                   180519 non-null  object
 44  Product Price                  180519 non-null  float64
 45  Product Status                 180519 non-null  int64
 46  shipping date (DateOrders)     180519 non-null  object
 47  Shipping Mode                  180519 non-null  object
 48  order date                     180519 non-null  datetime64[ns]
 49  order_date formatted           180519 non-null  datetime64[ns]
 50  order_date_formatted           180519 non-null  datetime64[ns]
 51  order_year                     180519 non-null  int32
dtypes: datetime64[ns](4), float64(13), int32(1), int64(14), object(20)
memory usage: 70.9+ MB

### FEATURE ENGINEERING

#Christmas column

In [ ]:
print(len(df.columns))

53